name: Build and Sign Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build APK
        run: gradle assembleRelease --stacktrace

      - name: Download apksigner
        run: sudo apt-get update && sudo apt-get install -y apksigner zipalign

      - name: Sign APK
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > my-release-key.jks
          zipalign -v -p 4 app/build/outputs/apk/release/app-release-unsigned.apk app-release-unsigned-aligned.apk
          apksigner sign --ks my-release-key.jks --ks-pass pass:$KEYSTORE_PASSWORD --key-pass pass:$KEY_PASSWORD --out app-release-signed.apk app-release-unsigned-aligned.apk

      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: SalaryCalculatorApp-Signed-APK
          path: app-release-signed.apk
